name: Verify

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno run -A main.ts

  test-macos:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno run -A main.ts
