name: Verify

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  test-ubuntu-deno:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno run -A main.ts

  test-macos-deno:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno run -A main.ts

  test-ubuntu-node:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - run: node --no-warnings=ExperimentalWarning main.ts

  test-macos-node:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - run: node --no-warnings=ExperimentalWarning main.ts
